### ISSUE TITLE
Arregla tu chingadera

### ISSUE THREAD

**Issue by Warmen2012** [AndratVA/Mario-Kart-64-HD#13]
Baje tus pinches texturas y a la hora de abrir el archivo zip, tu mierda no se abre, ya lo bajo como 10 veces y no sirve deberias de revisar eso,pendejo.

**Comment by GhostlyDark** [comment]
1) Don't use swear swords
2) Don't open multiple issues about the same problem
3) Use English
4) Check https://evilgames.eu for mirror links
