### ISSUE TITLE
Not Well Detailed Tutorial 

### ISSUE THREAD

**Issue by Celsio137** [AndratVA/Mario-Kart-64-HD#15]
Good Morning, I had a problem trying to install the game. I use this video (https://www.youtube.com/watch?v=szqfAfAJqCg) to install but I couldn't , because the tutorial of this site and the video is not well detailed.
I am very idiot talking about the technology and computers, so even if the intructions are logical for someone that knows how to use the basic of an computer I'm not that person, so please make a video or make hiper detailed tutorial.

+ There is 3 problems. The first problem that happened to me was that when the youtuber telled to "Choose ROM Directory" and click to the folder "roms" nothing happens, nothing to click, and the folder hasn't that "arrow" on the left sight like on the video.
![tela branca](https://user-images.githubusercontent.com/113327739/189576857-b1fde2c7-db00-476c-b1b4-d6a19948cd5f.png)
![foto9](https://user-images.githubusercontent.com/113327739/189577848-b97937f0-9f58-4c8f-a6c7-6e7e25de51a7.png)

+ The another problem (at least I think is) is that when I click over the Graphic pack this shows, not an the WinRar folders
![foto 1](https://user-images.githubusercontent.com/113327739/189577528-3d3267d6-a746-42dc-ba09-d906ce1d5580.png)
![foto 2](https://user-images.githubusercontent.com/113327739/189577530-495af2d2-adac-4003-9a7a-9b9f55914aac.png)
![foto 3](https://user-images.githubusercontent.com/113327739/189577532-77e6db34-3818-40c9-b779-6d90273f9000.png)

+ Well, the last topic is that on the video when finish to put the Graphic pack on the "hires_texture" folder, this folder dissapear and when I done this didn't happen. Like I said, I'm not an expert on computers so this might be some stupidity by my part.
![foto 12](https://user-images.githubusercontent.com/113327739/189578346-cc05e1ce-f566-4a9e-ae70-5d7dde985a7a.png)
![foto 13](https://user-images.githubusercontent.com/113327739/189578359-a3844cb1-99c3-4a3a-af6c-3e798c419f79.png)

Well, I'd like to play this incredible game, so please teach me how to install properly the game, Thank you all.

**Comment by CurryOnPatat** [comment]
unpack the zip and then rename it MARIOKART64

**Comment by TacoFromTheWind** [comment]
um, how many gigabytes is this?

**Comment by Nes-player4Life** [comment]
> um, how many gigabytes is this?

3.3 

![image](https://user-images.githubusercontent.com/10325597/199354139-2cce77b8-165c-4a57-a97a-6be2695f59b0.png)

**Comment by P3rf3ctXZer0** [comment]
You are one folder too deep as well.

**Comment by progman32** [comment]
A helpful user made a tutorial, which is being reviewed. It may be read here: https://github.com/AndratVA/Mario-Kart-64-HD/blob/9049f1105bd5c358bfd74a9aab626d262a0b3d87/README.md
