### ISSUE TITLE
Red shell missing sprite?

### ISSUE THREAD

**Issue by mbrozzo** [AndratVA/Mario-Kart-64-HD#16]
Hello, I may be reporting an already fixed issue, please excuseme if that is the case.

In this video [(LINK)](https://www.youtube.com/watch?v=ttLwl8RlDRk), the red shell is using an old texture for 1 frame of its rotation animation. I don't know if it applies to the green shell too.

![image](https://user-images.githubusercontent.com/22538059/201246887-c7acf513-0702-46fb-8593-326cb86fb941.png)
Edit: added reference image.

**Comment by GhostlyDark** [comment]
You need an up-to-date version of GLideN64 for `texture wildcards` to work. Release 4.0 is too old.
See https://github.com/gonetz/GLideN64/commit/31b38a7a2bdf4d9cfbe9dc928e3a385866f2c32f

**Comment by mbrozzo** [comment]
Thank you for the info!
