### ISSUE TITLE
Potentially enhanced tracks?

### ISSUE THREAD

**Issue by ObsidianPlague** [AndratVA/Mario-Kart-64-HD#17]
It'd be nice to get some modified tracks to add more details (like baked in lighting for example, giving fences no longer sprites, etc.)
Obviously they couldn't be _super_ detailed since you'd have to work within N64 emulator limitations, but it'd be nice to have, anyway

**Comment by GhostlyDark** [comment]
This is a texture pack. It can only replace textures on the fly. What you are asking for is modifying the game, which is outside of the scope of this project.

**Comment by ObsidianPlague** [comment]
aight, i getchya
