### ISSUE TITLE
No mention of emulator required(?)

### ISSUE THREAD

**Issue by filevans** [AndratVA/Mario-Kart-64-HD#18]
you don't even mention if this is standalone or for an emulator / which emulator, just put high res textures in a folder, AND?????

**Comment by P3rf3ctXZer0** [comment]
https://www.youtube.com/watch?v=lkHf73pH7eU

https://www.youtube.com/watch?v=fBl75uivS5M

https://www.youtube.com/watch?v=Vf7ufcnFa4s

**Comment by DamianS-eng** [comment]
Good to know that any emulator with GlideN64 texture pack support will work with this pack, but that is no excuse for lousy documentation. You can't assume that everyone who stumbles on this project has used texture packs before. Dedicate some time to write a thorough process on how to implement this specific texture pack. Video links to outdated guides are not going to cut it.

**Comment by P3rf3ctXZer0** [comment]
Lol okay captain

**Comment by gfriesen98** [comment]
wow sounds like u guys really want people to use this lmfao. just pull the readme request its that easy

**Comment by AndratVA** [comment]
This issue will be addressed in the coming days. I am out of town and thus cannot create a well thought out documentation. When I get home, however, that will be goal #1. In the meantime, I suggest trying Rosalie241's BetterMajorasMaskInstaller- it streamlines the process of installing texture packs like this one into 4 button presses, leaving you with a newly set up emulator and the texture pack all set up for you. Hope this helps :)

**Comment by filevans** [comment]
> this is not a question of emulator. If your video plugin for your preferred emulator supports texture packs - it will work.

You don't explain any of this in your read me. Do you expect people to read your mind?

**Comment by DamianS-eng** [comment]
[This is the auto-installer.](https://github.com/Rosalie241/BetterMajorasMaskInstaller)
Nerrel's MM HD tutorial goes through steps on setting it up via this installer, but instead of selecting MMN64HD, Mario Kart 64 HD should be an option. Choose that instead, and the emulator will all be set up for you.
[Nerrel's Tutorial](https://youtu.be/ovknYMdIp9I)
