### ISSUE TITLE
Compilation cache stutters

### ISSUE THREAD

**Issue by Tasosgemah** [AndratVA/Mario-Kart-64-HD#21]
When i use the pack with any emulator (standalone or RetroArch) the game stutters very intensely because of the shader compilation. After a while the stutters clear up and the game is smooth. But if i restart the computer, the stutters come back and the shaders are re-complile from scratch.

I'm using Windows 10 on an i5 4670, 16GB RAM and 1060 6GB.

**Comment by jgazzara1** [comment]
How did you end up resolving this issue? I am experiencing something similar. Thanks.

**Comment by jgazzara1** [comment]
Great. Thank you. One cause of our issue was the HD texture pack subfolder was selected as a main texture pack folder for project 64. Once we selected the general texture pack folder, it fixed our issue.
