### ISSUE TITLE
correct software, tools version for Windows?

### ISSUE THREAD

**Issue by epikao** [AndratVA/Mario-Kart-64-HD#22]
Hello,

I'm using project64 and mariokart.
Now I tried to update to HD with your software/tool, but unfortunately without success, also my folders looks a little different, for example I don't have a folder with "hires_texture"....

So I have some questions:
Which project64 version for Windows should work?
Which ROM Mariokart version should work?
And does project64 need additional tools as GlideN64, if yes which version should work, how include, activate?

I would appreciate any hints.

Thank you

**Edit:**
I also tried mupen64plus, but can't find following in the config-file:
txHiresTextureFileStorage

**Comment by xi7** [comment]
this work with android emulator ?

**Comment by GhostlyDark** [comment]
This texture pack works with virtually any N64 emulator that supports GLideN64, including ones available for Android.
