### ISSUE TITLE
Zip file is corrupted

### ISSUE THREAD

**Issue by DoominalCrossing** [AndratVA/Mario-Kart-64-HD#23]
The current zip file (March 10th update) is corrupted. When extracted using the default windows extractor it doesn't read any contents. When using 7Zip it encounters an error in either the DK or Bowser folders during various attempts.
![Extracterror](https://github.com/AndratVA/Mario-Kart-64-HD/assets/139725689/18b0f274-c557-411c-b96f-e3e8186c3729)
![7ziperror](https://github.com/AndratVA/Mario-Kart-64-HD/assets/139725689/a3019913-8f65-4441-9972-027528a5481e)

**Comment by GhostlyDark** [comment]
Uploaded .zip files aren't corrupted. Try to decompress onto a different (shorter) path. Don't do drag and drop with the files inside the archive, instead select "Extract here" by right clicking the archive file.

**Comment by DoominalCrossing** [comment]
I'm still having issues. I moved the zip folder to an isolated SSD to create the shortest possible file pathway, extracting in the same location but I still cannot fully extract the DK folder. I tried just that folder as well as the entire package with no luck. All of the other folders have extracted successfully though.
![dkerror](https://github.com/AndratVA/Mario-Kart-64-HD/assets/139725689/46335518-d043-4d0c-8a5a-dacde6554b4f)

**Comment by GhostlyDark** [comment]
The .zip file you downloaded is corrupted, but it's none of the release files. Downloading the source from GitHub directly doesn't seem to work reliably for a lot of users. You can clone the repository with something like GitHub Desktop, which should make sure that files don't end up being corrupted.

Alternatively, download files from either:
https://github.com/AndratVA/Mario-Kart-64-HD/releases
https://evilgames.eu/texture-packs/mario-kart-64-hd.htm
